library(descr)
describe(rdt$n_days_fb)
describe(rdt$fb_cumul)
lkf(rdt,"pf")
str(rdt)
with(rdt, lapply(list(pao2_24kpa, pao2_1kpa), describe))
lkf(rdt,"rrt")
with(wdt,names(fio2.1))
str(wdt[,.(rrt.1, rrt.24)])
sapply(wdt[,.(rrt.1, rrt.24)], descr)
